import bias
import Brownian
import coregionalise
import exponential
import finite_dimensional
import fixed
import independent_outputs
import linear
import Matern32
import Matern52
import periodic_exponential
import periodic_Matern32
import periodic_Matern52
import prod_orthogonal
import prod
import rational_quadratic
import rbfcos
import rbf
import spline
import symmetric
import white
